artist:
  name: Wyatt Olney & The Wreckage
  tagline: Seattle WA
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone:
  # contact_email:

social:
  - name: Facebook
    url: https://www.facebook.com/wyattolneyandthewreckage/
  - name: Instagram
    url: https://www.instagram.com/wyattolneyandthewreckage/
  - name: Youtube
    url: https://www.youtube.com/user/BurnTheWitchMusic
  - name: Spotify
    url: https://open.spotify.com/artist/3ExbLuST1For3zEAbbzNWC
  # - name: Twitter
  #   url: https://twitter.com

site_language: en
