navigation:
  - text: Releases
    url: "#releases"
  - text: Tour Dates
    url: "#tour-dates"
  - text: Booking
    url: "#booking"
  # TODO: Bio will be added in an upcoming feature
  # - text: Bio
  #   url: "#bio"
